FROM datomic

# Datomic

RUN apk add --no-cache maven
WORKDIR /opt/datomic
RUN bin/maven-install

# App

WORKDIR /opt/app

ADD project.clj ./

RUN lein deps

ADD src ./src

RUN UBERJAR_NAME=app.jar lein ring uberjar

CMD java -jar target/uberjar/app.jar
