FROM node:alpine

RUN apk add --no-cache rsync

WORKDIR /opt/frontend

ADD ["package.json", "yarn.lock", "./"]

RUN yarn

ADD src-js ./src-js
ADD src-scss ./src-scss
ADD *.js ./

RUN yarn run front-build-prod

CMD rsync -r --delete public /opt/ && tail -f /dev/null
