#!/usr/bin/env /bin/sh

# Usage:
#   ./use-env .prod.env
#   docker-compose up --build
#   Ctrl+D

name=$1

if [ ! $# -eq 1 ]; then
  echo "Expected one argument, got $#, aborting." >> /dev/stderr
  exit 1
fi

if [ ! -f $name ]; then
  echo "Env file $name not found, aborting." >> /dev/stderr
  exit 1
fi

set -a &&\
source $name &&\
set +a &&\
echo "Starting subshell with $name" &&\
exec $SHELL -l
